name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Lint with Pylint
      run: |
        pylint src/app.py
    - name: Test with unittest
      run: |
        python -m unittest discover -s src/tests
    - name: Integration Tests
      run: |
        python -m unittest src/tests/integration_tests.py
