name: Deploy Docker Container to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/sharara99/your-image-name:latest

      - name: Deploy to Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
